language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - hhvm

install:
  - composer install --dev --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=psr2 ./src

after_script:
  - ./vendor/bin/coveralls -v --exclude-no-stmt
